# Generated by Django 4.2.2 on 2023-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TP3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('modelo', models.CharField(max_length=15)),
                ('equipación', models.CharField(max_length=10)),
                ('talle', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('equipación', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('talle', models.CharField(max_length=4)),
            ],
        ),
    ]
