# Generated by Django 4.2.2 on 2023-06-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_TP3', '0002_abrigo_pantalon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abrigo',
            name='equipación',
        ),
    ]
